ALTER TABLE briefs ADD COLUMN IF NOT EXISTS is_shared BOOLEAN DEFAULT FALSE;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS share_key TEXT UNIQUE;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS is_edited BOOLEAN DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_briefs_share_key ON briefs(share_key) WHERE share_key IS NOT NULL;
